// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_lazyarray_RCPPEXPORTS_H_GEN_
#define RCPP_lazyarray_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace lazyarray {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("lazyarray", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("lazyarray", "_lazyarray_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in lazyarray");
            }
        }
    }

    inline int getLazyThread() {
        typedef SEXP(*Ptr_getLazyThread)();
        static Ptr_getLazyThread p_getLazyThread = NULL;
        if (p_getLazyThread == NULL) {
            validateSignature("int(*getLazyThread)()");
            p_getLazyThread = (Ptr_getLazyThread)R_GetCCallable("lazyarray", "_lazyarray_getLazyThread");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_getLazyThread();
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<int >(rcpp_result_gen);
    }

    inline int setLazyThread(int n, SEXP reset_after_fork = R_NilValue) {
        typedef SEXP(*Ptr_setLazyThread)(SEXP,SEXP);
        static Ptr_setLazyThread p_setLazyThread = NULL;
        if (p_setLazyThread == NULL) {
            validateSignature("int(*setLazyThread)(int,SEXP)");
            p_setLazyThread = (Ptr_setLazyThread)R_GetCCallable("lazyarray", "_lazyarray_setLazyThread");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_setLazyThread(Shield<SEXP>(Rcpp::wrap(n)), Shield<SEXP>(Rcpp::wrap(reset_after_fork)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<int >(rcpp_result_gen);
    }

    inline bool hasOpenMP() {
        typedef SEXP(*Ptr_hasOpenMP)();
        static Ptr_hasOpenMP p_hasOpenMP = NULL;
        if (p_hasOpenMP == NULL) {
            validateSignature("bool(*hasOpenMP)()");
            p_hasOpenMP = (Ptr_hasOpenMP)R_GetCCallable("lazyarray", "_lazyarray_hasOpenMP");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_hasOpenMP();
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<bool >(rcpp_result_gen);
    }

}

#endif // RCPP_lazyarray_RCPPEXPORTS_H_GEN_
