# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setLazyBlockSize <- function(size) {
    .Call(`_lazyarray_setLazyBlockSize`, size)
}

getLazyBlockSize <- function() {
    .Call(`_lazyarray_getLazyBlockSize`)
}

fstMeta <- function(fileName) {
    .Call(`_lazyarray_fstMeta`, fileName)
}

fstRetrieve <- function(fileName, colSel, start, end) {
    .Call(`_lazyarray_fstRetrieve`, fileName, colSel, start, end)
}

fstStore <- function(fileName, table, compression, uniformEncoding) {
    .Call(`_lazyarray_fstStore`, fileName, table, compression, uniformEncoding)
}

checkFstMeta <- function(file, expect_nrows, cnames) {
    .Call(`_lazyarray_checkFstMeta`, file, expect_nrows, cnames)
}

loc2idx3 <- function(locations, parent_dim) {
    .Call(`_lazyarray_loc2idx3`, locations, parent_dim)
}

extractSlices <- function(listOrEnv, ndims) {
    .Call(`_lazyarray_extractSlices`, listOrEnv, ndims)
}

parseSlices <- function(listOrEnv, dim, pos_subscript = TRUE) {
    .Call(`_lazyarray_parseSlices`, listOrEnv, dim, pos_subscript)
}

parseAndScheduleBlocks2 <- function(sliceIdx, dim, forceSchedule = FALSE) {
    .Call(`_lazyarray_parseAndScheduleBlocks2`, sliceIdx, dim, forceSchedule)
}

reshapeOrDrop <- function(x, reshape = NULL, drop = FALSE) {
    .Call(`_lazyarray_reshapeOrDrop`, x, reshape, drop)
}

cpp_create_lazyarray <- function(x, dim, fileName, compression, uniformEncoding) {
    .Call(`_lazyarray_cpp_create_lazyarray`, x, dim, fileName, compression, uniformEncoding)
}

lazyMapReduceByPartition <- function(fileName, colSel, start, end = NULL, custom_func = NULL, reshape = NULL) {
    .Call(`_lazyarray_lazyMapReduceByPartition`, fileName, colSel, start, end, custom_func, reshape)
}

lazyLoadOld <- function(files, partition_locations, partition_dim, ndim, value_type) {
    .Call(`_lazyarray_lazyLoadOld`, files, partition_locations, partition_dim, ndim, value_type)
}

subsetFST <- function(rootPath, listOrEnv, dim, dtype, reshape = NULL, drop = FALSE) {
    .Call(`_lazyarray_subsetFST`, rootPath, listOrEnv, dim, dtype, reshape, drop)
}

scheduleFST <- function(listOrEnv, dim, forceSchedule = FALSE, hint = -1L) {
    .Call(`_lazyarray_scheduleFST`, listOrEnv, dim, forceSchedule, hint)
}

executeScheduleFST <- function(rootPath, dtype, reshape, drop, partition) {
    .Call(`_lazyarray_executeScheduleFST`, rootPath, dtype, reshape, drop, partition)
}

scheduleExistsFST <- function() {
    .Call(`_lazyarray_scheduleExistsFST`)
}

freeScheduleFST <- function() {
    .Call(`_lazyarray_freeScheduleFST`)
}

getLazyThread <- function(max = FALSE) {
    .Call(`_lazyarray_getLazyThread`, max)
}

setLazyThread <- function(n, reset_after_fork = NULL) {
    .Call(`_lazyarray_setLazyThread`, n, reset_after_fork)
}

hasOpenMP <- function() {
    .Call(`_lazyarray_hasOpenMP`)
}

subsetAssignFST <- function(values, file, listOrEnv, dim, dtype, compression = 50L, uniformEncoding = TRUE) {
    .Call(`_lazyarray_subsetAssignFST`, values, file, listOrEnv, dim, dtype, compression, uniformEncoding)
}

dropDimension <- function(x) {
    .Call(`_lazyarray_dropDimension`, x)
}

prod2 <- function(x, na_rm = FALSE) {
    .Call(`_lazyarray_prod2`, x, na_rm)
}

parseDots <- function(env, eval) {
    .Call(`_lazyarray_parseDots`, env, eval)
}

stopIfNot <- function(isValid, message, stopIfError = TRUE) {
    .Call(`_lazyarray_stopIfNot`, isValid, message, stopIfError)
}

getSexpType <- function(x) {
    .Call(`_lazyarray_getSexpType`, x)
}

tik <- function() {
    .Call(`_lazyarray_tik`)
}

tok <- function(msg, stop = FALSE) {
    .Call(`_lazyarray_tok`, msg, stop)
}

subsetAssignVector <- function(x, start, value) {
    .Call(`_lazyarray_subsetAssignVector`, x, start, value)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_lazyarray_RcppExport_registerCCallable', PACKAGE = 'lazyarray')
})
