# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

subsetBM <- function(pBigMat, listOrEnv, dim, reshape = NULL, drop = FALSE) {
    .Call(`_lazyarray_subsetBM`, pBigMat, listOrEnv, dim, reshape, drop)
}

setLazyBlockSize <- function(size) {
    .Call(`_lazyarray_setLazyBlockSize`, size)
}

getLazyBlockSize <- function() {
    .Call(`_lazyarray_getLazyBlockSize`)
}

fstMeta <- function(fileName) {
    .Call(`_lazyarray_fstMeta`, fileName)
}

fstRetrieve <- function(fileName, colSel, start, end) {
    .Call(`_lazyarray_fstRetrieve`, fileName, colSel, start, end)
}

fstStore <- function(fileName, table, compression, uniformEncoding) {
    .Call(`_lazyarray_fstStore`, fileName, table, compression, uniformEncoding)
}

checkFstMeta <- function(file, expect_nrows, cnames) {
    .Call(`_lazyarray_checkFstMeta`, file, expect_nrows, cnames)
}

loc2idx <- function(locations, parent_dim) {
    .Call(`_lazyarray_loc2idx`, locations, parent_dim)
}

loc2idx2 <- function(locations, parent_dim) {
    .Call(`_lazyarray_loc2idx2`, locations, parent_dim)
}

loc2idx3 <- function(locations, parent_dim) {
    .Call(`_lazyarray_loc2idx3`, locations, parent_dim)
}

subsetIdx <- function(expr_env, dim, pos_subscript = FALSE) {
    .Call(`_lazyarray_subsetIdx`, expr_env, dim, pos_subscript)
}

subsetIdx2 <- function(sliceIdx, dim, pos_subscript = FALSE) {
    .Call(`_lazyarray_subsetIdx2`, sliceIdx, dim, pos_subscript)
}

scheduleIndexing <- function(locations, dimension) {
    .Call(`_lazyarray_scheduleIndexing`, locations, dimension)
}

parseAndScheduleBlocks <- function(sliceIdx, dim) {
    .Call(`_lazyarray_parseAndScheduleBlocks`, sliceIdx, dim)
}

reshapeOrDrop <- function(x, reshape = NULL, drop = FALSE) {
    .Call(`_lazyarray_reshapeOrDrop`, x, reshape, drop)
}

cpp_create_lazyarray <- function(x, dim, fileName, compression, uniformEncoding) {
    .Call(`_lazyarray_cpp_create_lazyarray`, x, dim, fileName, compression, uniformEncoding)
}

lazyMapReduceByPartition <- function(fileName, colSel, start, end = NULL, custom_func = NULL, reshape = NULL) {
    .Call(`_lazyarray_lazyMapReduceByPartition`, fileName, colSel, start, end, custom_func, reshape)
}

lazyLoadOld <- function(files, partition_locations, partition_dim, ndim, value_type) {
    .Call(`_lazyarray_lazyLoadOld`, files, partition_locations, partition_dim, ndim, value_type)
}

lazySubsetBare <- function(files, dim, subparsed, dtype, reshape = NULL, drop = FALSE) {
    .Call(`_lazyarray_lazySubsetBare`, files, dim, subparsed, dtype, reshape, drop)
}

lazySubset <- function(files, env, dim, samp, reshape = NULL, drop = FALSE) {
    .Call(`_lazyarray_lazySubset`, files, env, dim, samp, reshape, drop)
}

getLazyThread <- function(max = FALSE) {
    .Call(`_lazyarray_getLazyThread`, max)
}

setLazyThread <- function(n, reset_after_fork = NULL) {
    .Call(`_lazyarray_setLazyThread`, n, reset_after_fork)
}

hasOpenMP <- function() {
    .Call(`_lazyarray_hasOpenMP`)
}

asi <- function(v, nt) {
    .Call(`_lazyarray_asi`, v, nt)
}

playground <- function(x) {
    .Call(`_lazyarray_playground`, x)
}

dropDimension <- function(x) {
    .Call(`_lazyarray_dropDimension`, x)
}

prod2 <- function(x, na_rm = FALSE) {
    .Call(`_lazyarray_prod2`, x, na_rm)
}

parseDots <- function(env, eval) {
    .Call(`_lazyarray_parseDots`, env, eval)
}

stopIfNot <- function(isValid, message, stopIfError = TRUE) {
    .Call(`_lazyarray_stopIfNot`, isValid, message, stopIfError)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_lazyarray_RcppExport_registerCCallable', PACKAGE = 'lazyarray')
})
